android v2 initial release
imobile/MaioSDK-v2-Android pull request #1
Opened 2024-09-18 00:15 UTC by im-ade

2024-09-18 01:35 UTC, 7pairs requested changes
いくつか指摘をしましたので、確認をお願いします。

2024-09-18 01:35 UTC, 7pairs commented on readme.md
> +kotlinの古いバージョンの場合/For older kotlin projects:
`libs.versions.toml` を使うライブラリの指定方法は、
KotlinのバージョンというよりはGradleのバージョンに依存する機能で、
バージョンカタログという名前がついています。

なので、タイトルは以下のように修正した方が良いかと思います。

- Kotlinの古いバージョンの場合 -> バージョンカタログを使用しない場合
- Kotlinの新しいバージョンの場合 -> バージョンカタログを使用する場合

2024-09-18 01:35 UTC, 7pairs commented on readme.md
> +    implementation 'com.maio:android-sdk-v2:2.0.0'
末尾に `@aar` をつけるのはPlay Servicesではなくmaio SDKのほうではないでしょうか？

2024-09-18 01:35 UTC, 7pairs commented on readme.md
> +- maioを導入したいプロジェクトの`settings.gradle.kts`に、以下のmavenリポジトリを追加します。
`settings.gradle.kts` ではなく `libs.versions.toml` に記述する内容かと思います。

2024-09-18 05:59 UTC, sfukui66 requested changes

2024-09-18 05:59 UTC, sfukui66 commented on readme.md
> +    implementation(libs.maio.android.sdk@aar)
バージョンカタログを使用してaarを指定する場合、下記のように記載する必要がありました。
```
implementation(libs.maio.android.sdk) {
    artifact {
        type = "aar"
    }
}
```
参考：https://zenn.dev/yagiryuuu/articles/bcd7b862ca00ba

2024-09-25 05:59 UTC, sfukui66 approved these changes
LGTMです。

2024-09-25 06:40 UTC, 7pairs approved these changes
LGTM👍

2024-09-25 09:56 UTC, im-higashi approved these changes
LGTM 🙆 
@im-ade マージお願いします、ビジネス側へMAXへの通知依頼お願いします
@7pairs AdMob 対応お願いします

2024-09-25 10:20 UTC, merged